/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import proyectoso.Central;

/**
 *
 * @author LStanislao
 */
public class PersonalDeLaFabrica extends javax.swing.JFrame {

    /**
     * Creates new form PersonalDeLaFabrica
     */
    public PersonalDeLaFabrica() {
        initComponents();
        ProductoresBotones.setText( Integer.toString(Central.manejadorDePersonal.numProBotones));
        ProductoresPantallas.setText( Integer.toString(Central.manejadorDePersonal.numProPantallas));
        ProductoresTarjetas.setText( Integer.toString(Central.manejadorDePersonal.numProTarjetasSD));
        ProductoresJoystick.setText( Integer.toString(Central.manejadorDePersonal.numProJoystick));   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ProductoresBotones = new javax.swing.JLabel();
        ProductoresPantallas = new javax.swing.JLabel();
        ProductoresJoystick = new javax.swing.JLabel();
        ProductoresTarjetas = new javax.swing.JLabel();
        ContratarProBotones = new javax.swing.JButton();
        DespedirProBotones = new javax.swing.JButton();
        ContrarProPantallas = new javax.swing.JButton();
        ContratarProJoystick = new javax.swing.JButton();
        ContratarProTarjetasSD = new javax.swing.JButton();
        DespedirProPantallas = new javax.swing.JButton();
        DespedirProJoystick = new javax.swing.JButton();
        DespedirProTarjetasSD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Administrar personal de la fábrica");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel7.setText("Productores de botones:");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel9.setText("Productores de Pantallas:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel10.setText("Productores de Joysticks:");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel11.setText("Productores de Tarjetas SD:");

        ProductoresBotones.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ProductoresBotones.setText("0");

        ProductoresPantallas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ProductoresPantallas.setText("0");

        ProductoresJoystick.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ProductoresJoystick.setText("0");

        ProductoresTarjetas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        ProductoresTarjetas.setText("0");

        ContratarProBotones.setText("Contratar");
        ContratarProBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratarProBotonesActionPerformed(evt);
            }
        });

        DespedirProBotones.setText("Despedir");
        DespedirProBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirProBotonesActionPerformed(evt);
            }
        });

        ContrarProPantallas.setText("Contratar");
        ContrarProPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrarProPantallasActionPerformed(evt);
            }
        });

        ContratarProJoystick.setText("Contratar");
        ContratarProJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratarProJoystickActionPerformed(evt);
            }
        });

        ContratarProTarjetasSD.setText("Contratar");
        ContratarProTarjetasSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratarProTarjetasSDActionPerformed(evt);
            }
        });

        DespedirProPantallas.setText("Despedir");
        DespedirProPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirProPantallasActionPerformed(evt);
            }
        });

        DespedirProJoystick.setText("Despedir");
        DespedirProJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirProJoystickActionPerformed(evt);
            }
        });

        DespedirProTarjetasSD.setText("Despedir");
        DespedirProTarjetasSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirProTarjetasSDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProductoresTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProductoresJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProductoresPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(40, 40, 40)
                        .addComponent(ProductoresBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContratarProBotones)
                    .addComponent(ContrarProPantallas)
                    .addComponent(ContratarProJoystick)
                    .addComponent(ContratarProTarjetasSD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DespedirProBotones, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DespedirProPantallas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DespedirProJoystick, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DespedirProTarjetasSD, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ProductoresBotones)
                    .addComponent(ContratarProBotones)
                    .addComponent(DespedirProBotones))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ProductoresPantallas)
                    .addComponent(ContrarProPantallas)
                    .addComponent(DespedirProPantallas))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ProductoresJoystick)
                    .addComponent(ContratarProJoystick)
                    .addComponent(DespedirProJoystick))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ProductoresTarjetas)
                    .addComponent(ContratarProTarjetasSD)
                    .addComponent(DespedirProTarjetasSD))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContratarProBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratarProBotonesActionPerformed

    }//GEN-LAST:event_ContratarProBotonesActionPerformed

    private void DespedirProBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirProBotonesActionPerformed
        Central.manejadorDePersonal.DespedirProBotones();
    }//GEN-LAST:event_DespedirProBotonesActionPerformed

    private void ContrarProPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrarProPantallasActionPerformed
         Central.manejadorDePersonal.ContratarProPantallas();
    }//GEN-LAST:event_ContrarProPantallasActionPerformed

    private void ContratarProJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratarProJoystickActionPerformed
        Central.manejadorDePersonal.ContratarProJoystick();
    }//GEN-LAST:event_ContratarProJoystickActionPerformed

    private void ContratarProTarjetasSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratarProTarjetasSDActionPerformed
        Central.manejadorDePersonal.ContratarProTarjetasSD();
    }//GEN-LAST:event_ContratarProTarjetasSDActionPerformed

    private void DespedirProPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirProPantallasActionPerformed
        Central.manejadorDePersonal.DespedirProPantallas();
    }//GEN-LAST:event_DespedirProPantallasActionPerformed

    private void DespedirProJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirProJoystickActionPerformed
        Central.manejadorDePersonal.DespedirProJoystick();
    }//GEN-LAST:event_DespedirProJoystickActionPerformed

    private void DespedirProTarjetasSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirProTarjetasSDActionPerformed
        Central.manejadorDePersonal.DespedirProTarjetasSD();
    }//GEN-LAST:event_DespedirProTarjetasSDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalDeLaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalDeLaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalDeLaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalDeLaFabrica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalDeLaFabrica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContrarProPantallas;
    private javax.swing.JButton ContratarProBotones;
    private javax.swing.JButton ContratarProJoystick;
    private javax.swing.JButton ContratarProTarjetasSD;
    private javax.swing.JButton DespedirProBotones;
    private javax.swing.JButton DespedirProJoystick;
    private javax.swing.JButton DespedirProPantallas;
    private javax.swing.JButton DespedirProTarjetasSD;
    private javax.swing.JLabel ProductoresBotones;
    private javax.swing.JLabel ProductoresJoystick;
    private javax.swing.JLabel ProductoresPantallas;
    private javax.swing.JLabel ProductoresTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
